// Register
export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';

//Login
export const LOG_IN = 'LOG_IN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//Logout
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

//Get Comment
export const GET_COMMENT = 'GET_COMMENT';
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';
export const GET_COMMENT_FAILURE = 'GET_COMMENT_FAILURE';

//Get comment by id
export const GET_COMMENT_DETAIL = 'GET_COMMENT_DETAIL';
export const GET_COMMENT_DETAIL_SUCCESS = 'GET_COMMENT_DETAIL_SUCCESS';

// Update comment
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';

//Add a comment on book
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';

//Related Books
export const GET_RELATED_BOOK = 'GET_RELATED_BOOK';
export const GET_RELATED_BOOK_SUCCESS = 'GET_RELATED_BOOK_SUCCESS';

//Get List of Books
export const GET_BOOK = 'GET_BOOK';
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const GET_BOOK_FAILURE = 'GET_BOOK_FAILURE';

//Get Book By Id
export const GET_BOOK_DETAIL = 'GET_BOOK_DETAIL';
export const GET_BOOK_DETAIL_SUCCESS = 'GET_BOOK_DETAIL_SUCCESS';

//Get best users
export const GET_BEST_USERS = 'GET_BEST_USERS';
export const GET_BEST_USERS_SUCCESS = 'GET_BEST_USERS_SUCCESS';
export const GET_BEST_USERS_FAILURE = 'GET_BEST_USERS_FAILURE';

//Get oustandingReviews
export const GET_OUSTANDING_REVIEWS = 'GET_OUSTANDING_REVIEWS';
export const GET_OUSTANDING_REVIEWS_SUCCESS = 'GET_OUSTANDING_REVIEWS_SUCCESS';
export const GET_OUSTANDING_REVIEWS_FAILURE = 'GET_OUSTANDING_REVIEWS_FAILURE';
